layout_spectrum: 0.6561242871175492
typography_spectrum: 0.5420997324050174
color:
  brandStrength: 0.7087866010259615
  lightness: 0.6677325606022473
  saturation: 0.1678864052135608
  rhythmicContrast: 0.36909809712873826
  brandColors:
    - '#FFFFFF'
    - '#046A38'
    - '#B9D2C7'
    - '#FCEB77'
    - '#6DA589'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Modern Arbor
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8719f54a-b01d-47ab-8392-996897e09824.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8719f54a-b01d-47ab-8392-996897e09824.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/33fc9d4a-65d7-4426-ae31-1fc7803a4305.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/33fc9d4a-65d7-4426-ae31-1fc7803a4305.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Modern Arbor
description: >-
  Welcome to the home of ethical tree care.  Modern Arbor Professional Tree
  Services
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00d41246-715f-474d-92d2-5426c7495c59.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/72c60879-9fa5-49c8-937d-1ca98a496259.png
purpose:
  - type: contact
    url: 'tel:0449150471'
    label: 0449150471
  - type: contact
    url: 'mailto:stuart@modernarbor.com'
    label: stuart@modernarbor.com
